// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddNode: typeof import('./src/components/addNode.vue')['default']
    ApproverDrawer: typeof import('./src/components/drawer/approverDrawer.vue')['default']
    BasicSetting: typeof import('./src/components/BasicSetting/index.vue')['default']
    ConditionDrawer: typeof import('./src/components/drawer/conditionDrawer.vue')['default']
    CopyerDrawer: typeof import('./src/components/drawer/copyerDrawer.vue')['default']
    DynamicForm: typeof import('./src/components/DynamicForm/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ErrorDialog: typeof import('./src/components/dialog/errorDialog.vue')['default']
    FormRender: typeof import('./src/components/DynamicForm/formRender.vue')['default']
    NodeWrap: typeof import('./src/components/nodeWrap.vue')['default']
    Process: typeof import('./src/components/Process/index.vue')['default']
    PromoterDrawer: typeof import('./src/components/drawer/promoterDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectRoleDialog: typeof import('./src/components/dialog/selectRoleDialog.vue')['default']
    SelectUserDialog: typeof import('./src/components/dialog/selectUserDialog.vue')['default']
    Toolbar: typeof import('./src/components/Process/toolbar.vue')['default']
  }
}
